runtime: php81

instance_class: F1

automatic_scaling:
  max_instances: 1
  min_instances: 0


handlers:
  # This automatically redirects to the front controller in index.php
  - url: .*
    script: auto
    secure: always
    redirect_http_response_code: 301


# [START gae_php_mysql_env]
env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: permit_me.json
  GOOGLE_CLOUD_PROJECT: Dashboard