runtime: php81

instance_class: F1

automatic_scaling:
  max_instances: 1
  min_instances: 0


handlers:
  - url: /static
    static_dir: static

  # This automatically redirects to the front controller in index.php
  - url: .*
    script: auto
    secure: always
    redirect_http_response_code: 301

# [START gae_php_mysql_env]
env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: permit_me.json
  GOOGLE_CLOUD_PROJECT: Dashboard
  MYSQL_HOST: mysql:unix_socket=/cloudsql/dashboard-397622:europe-west1:dashboard-db
  MYSQL_DB: dashboard_db
  MYSQL_LDB: dashboardlocal
  MYSQL_USER: root
  MYSQL_PASSWORD: 123456